# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': set([('read_asset', '\u53ea\u8bfb\u8d44\u4ea7\u7ba1\u7406')]), 'verbose_name': '\u8d44\u4ea7\u7ba1\u7406', 'verbose_name_plural': '\u8d44\u4ea7\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='asset',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='asset',
            name='func',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u529f\u80fd'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_down',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0b\u67b6'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manage_url',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ba1\u7406url'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manage_user',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u7ba1\u7406\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manage_user_passwd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7ba1\u7406\u7528\u6237\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='asset',
            name='server_info',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u670d\u52a1\u5668\u914d\u7f6e\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='server_admin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u767b\u9646\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='server_admin_passwd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u767b\u9646\u7528\u6237\u5bc6\u7801'),
        ),
    ]
